# ─── S3 — Report Storage ─────────────────────────────────────────────────────
#
# Stores generated HTML reports. The worker uploads each report and stores a
# pre-signed URL (7-day TTL) in DynamoDB for the customer to download.
#
# Bucket is private — all access is via pre-signed URLs generated by the worker.
# ─────────────────────────────────────────────────────────────────────────────

resource "aws_s3_bucket" "reports" {
  bucket = "${var.app_name}-reports"

  tags = { Name = "${var.app_name}-reports" }
}

resource "aws_s3_bucket_public_access_block" "reports" {
  bucket = aws_s3_bucket.reports.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Auto-delete reports after 30 days to control storage costs
resource "aws_s3_bucket_lifecycle_configuration" "reports" {
  bucket = aws_s3_bucket.reports.id

  rule {
    id     = "expire-reports"
    status = "Enabled"

    expiration {
      days = 30
    }
  }
}
